<!DOCTYPE html>
<html lang="en">
<head>
<title>Mostudio - Free Bootstrap 4 Template by Colorlib</title>
	<meta charset="utf-8">
        <base href="/localhost" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="../templates/mostudio/css/animate.css">
	
	<link rel="stylesheet" href="../templates/mostudio/css/owl.carousel.min.css">
	<link rel="stylesheet" href="../templates/mostudio/css/owl.theme.default.min.css">
	<link rel="stylesheet" href="../templates/mostudio/css/magnific-popup.css">

	
	<link rel="stylesheet" href="../templates/mostudio/css/flaticon.css">
	<link rel="stylesheet" href="../templates/mostudio/css/style.css">
</head>
<body>

	<div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="js-fullheight">

			<h1 id="colorlib-logo" class="mb-4 mb-md-5"><a href="template/most<?= $url ?>" style="background-image: url(../templates/mostudio/images/bg_1.jpg);">Mostudio</a></h1>
			<nav id="colorlib-main-menu" role="navigation">
				<ul>
					<li> <a href="template/most<?= $url ?>">Home</a></li>
					<li><a href="template/gallery_most<?= $url ?>">Gallery</a></li>
					<li class="colorlib-active"><a href="template/about_most<?= $url ?>">About</a></li>
					<li><a href="template/service_most<?= $url ?>">Services</a></li>
					<li><a href="template/contact_most<?= $url ?>">Contact</a></li>
				</ul>
			</nav>

			<div class="colorlib-footer">
				<div class="mb-4">
					<h3>Subscribe for newsletter</h3>
					<form action="#" class="colorlib-subscribe-form">
						<div class="form-group d-flex">
							<div class="icon"><span class="icon-paper-plane"></span></div>
							<input type="text" class="form-control" placeholder="Enter Email Address">
						</div>
					</form>
				</div>
				<p class="pfooter"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				</div>
			</aside> <!-- END COLORLIB-ASIDE -->
			<div id="colorlib-main">
				<section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
					<div class="container-fluid px-0">
						<div class="row d-flex">
							<div class="col-md-6 d-flex">
								<div class="img d-flex align-self-stretch align-items-center js-fullheight" style="background-image:url(../templates/mostudio/images/about.jpg);">
								</div>
							</div>
							<div class="col-md-6 d-flex align-items-center">
								<div class="text px-4 pt-5 pt-md-0 px-md-4 pr-md-5 ftco-animate">
									<h2 class="mb-4">Hello! I'm<span>
										<?php if (isset($jmeno)) : ?>
											<?= $jmeno ?>
										<?php else : ?>
											Ondřej Kropáč
										<?php endif ?>
										</span> from 
										<?php if (isset($titulek)) : ?>
											<?= $titulek ?>
										<?php else : ?>
											Pod_horama Photography
										<?php endif ?>
									</h2>
									<p>
										<?php if (isset($popis)) : ?>
											<?= $popis ?>
										<?php else : ?>
											Pod_horama Photography
										<?php endif ?>
										nebo další text... A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
									<!--div class="team-wrap row mt-4">
										<div class="col-md-4 team">
											<div class="img" style="background-image: url(images/team-1.jpg);"></div>
											<h3>John Doe</h3>
											<span>Photographer</span>
										</div>
										<div class="col-md-4 team">
											<div class="img" style="background-image: url(images/team-2.jpg);"></div>
											<h3>John Flex</h3>
											<span>Photographer</span>
										</div>
										<div class="col-md-4 team">
											<div class="img" style="background-image: url(images/team-3.jpg);"></div>
											<h3>John Flex</h3>
											<span>Photographer</span>
										</div>
									</div-->
								</div>
							</div>
						</div>
					</div>
				</section>
			</div><!-- END COLORLIB-MAIN -->
		</div><!-- END COLORLIB-PAGE -->

		<!-- loader -->
		<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


		<script src="../templates/mostudio/js/jquery.min.js"></script>
		<script src="../templates/mostudio/js/jquery-migrate-3.0.1.min.js"></script>
		<script src="../templates/mostudio/js/popper.min.js"></script>
		<script src="../templates/mostudio/js/bootstrap.min.js"></script>
		<script src="../templates/mostudio/js/jquery.easing.1.3.js"></script>
		<script src="../templates/mostudio/js/jquery.waypoints.min.js"></script>
		<script src="../templates/mostudio/js/jquery.stellar.min.js"></script>
		<script src="../templates/mostudio/js/owl.carousel.min.js"></script>
		<script src="../templates/mostudio/js/jquery.magnific-popup.min.js"></script>
		<script src="../templates/mostudio/js/jquery.animateNumber.min.js"></script>
		<script src="../templates/mostudio/js/scrollax.min.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
		<script src="../templates/mostudio/js/google-map.js"></script>
		<script src="../templates/mostudio/js/main.js"></script>
		
	</body>
	</html>