<!DOCTYPE html>
<html lang="en">
<head>
	<title>Mostudio - Free Bootstrap 4 Template by Colorlib</title>
	<meta charset="utf-8">
        <base href="/localhost" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="../templates/mostudio/css/animate.css">
	
	<link rel="stylesheet" href="../templates/mostudio/css/owl.carousel.min.css">
	<link rel="stylesheet" href="../templates/mostudio/css/owl.theme.default.min.css">
	<link rel="stylesheet" href="../templates/mostudio/css/magnific-popup.css">

	
	<link rel="stylesheet" href="../templates/mostudio/css/flaticon.css">
	<link rel="stylesheet" href="../templates/mostudio/css/style.css">
</head>
<body>

	<div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="js-fullheight">

			<h1 id="colorlib-logo" class="mb-4 mb-md-5"><a href="template/most<?= $url ?>" style="background-image: url(../templates/mostudio/images/bg_1.jpg);">Mostudio</a></h1>
			<nav id="colorlib-main-menu" role="navigation">
				<ul>
                <?= $url ?>
					<li class="colorlib-active"><a href="template/most<?= $url ?>">Home</a></li>
					<li><a href="template/gallery_most<?= $url ?>">Gallery</a></li>
					<li><a href="template/about_most<?= $url ?>">About</a></li>
					<li><a href="template/service_most<?= $url ?>">Services</a></li>
					<li><a href="template/contact_most<?= $url ?>">Contact</a></li>
					
					<?php $user = (isset($user_id)) ? $user_id : ''; ?>
					<li class="colorlib-active"><a href="template/all<?= $url ?>/<?= $user_id ?>#summary">Zpět na přehled</a></li>
				</ul>
			</nav>

			<div class="colorlib-footer">
				<div class="mb-4">
					<h3>Subscribe for newsletter</h3>
					<form action="#" class="colorlib-subscribe-form">
						<div class="form-group d-flex">
							<div class="icon"><span class="icon-paper-plane"></span></div>
							<input type="text" class="form-control" placeholder="Enter Email Address">
						</div>
					</form>
				</div>
				<p class="pfooter"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				</div>
			</aside> <!-- END COLORLIB-ASIDE -->
			<div id="colorlib-main">
				<section class="ftco-section ftco-no-pt ftco-no-pb">
					<div class="container px-md-0">
						<div class="row d-flex no-gutters">
							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/image/work-1.jpg" class="col-md-6 img image-popup js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-1.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 pl-0 px-lg-5 pl-md-4 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc">
													<div class="top">
														<span class="subheading">Architecture</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">Black &amp; White Photography</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/image/work-2.jpg" class="col-md-6 order-md-last img image-popup js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-2.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 px-md-5 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc text-md-right">
													<div class="top">
														<span class="subheading">Landscape</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">Green Leaves</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/image/work-3.jpg" class="col-md-6 img image-popup js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-3.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 pl-0 px-lg-5 pl-md-4 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc">
													<div class="top">
														<span class="subheading">Landscape</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">Energy</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/image/work-4.jpg" class="col-md-6 order-md-last img image-popup js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-4.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 px-md-5 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc text-md-right">
													<div class="top">
														<span class="subheading">Nature</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">Elements</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/images/work-5.jpg" class="col-md-6 img image-popup js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-5.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 pl-0 px-lg-5 pl-md-4 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc">
													<div class="top">
														<span class="subheading">Portrait</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">Building</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/images/work-6.jpg" class="col-md-6 order-md-last img image-popup js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-6.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 px-md-5 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc text-md-right">
													<div class="top">
														<span class="subheading">Fashion</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">City</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/images/work-7.jpg" class="col-md-6 img image-popup js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-7.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 pl-0 px-lg-5 pl-md-4 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc">
													<div class="top">
														<span class="subheading">Animals</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">Statue</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/images/work-8.jpg" class="col-md-6 order-md-last img image-popup js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-8.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 px-md-5 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc text-md-right">
													<div class="top">
														<span class="subheading">Nature</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">Evening</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="col-md-12 portfolio-wrap">
								<div class="row no-gutters align-items-center">
									<a href="../templates/mostudio/images/work-9.jpg" class="col-md-6 img js-fullheight d-flex align-items-center justify-content-center" style="background-image: url(../templates/mostudio/images/work-9.jpg);">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-expand"></span>
										</div>
									</a>
									<div class="col-md-6">
										<div class="text pt-5 pl-0 px-lg-5 pl-md-4 ftco-animate">
											<div class="px-4 px-lg-4">
												<div class="desc">
													<div class="top">
														<span class="subheading">Animals</span>
														<h2 class="mb-4"><a href="../templates/mostudio/gallery.html">Between landscape and history</a></h2>
													</div>
													<div class="absolute">
														<p>Průvodní text k nahrazení popisem.</p>
													</div>
													<p><a href="../templates/mostudio/single.html" class="custom-btn">View Portfolio</a></p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row d-flex">
							<div class="col-md-12">
								<a href="#" class="btn-custom-load d-block w-100 text-center py-4">Load more <span class="fa fa-refresh"></span></a>
							</div>
						</div>
					</div>
				</section>
			</div><!-- END COLORLIB-MAIN -->
		</div><!-- END COLORLIB-PAGE -->

		<!-- loader -->
		<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


		<script src="../templates/mostudio/js/jquery.min.js"></script>
		<script src="../templates/mostudio/js/jquery-migrate-3.0.1.min.js"></script>
		<script src="../templates/mostudio/js/popper.min.js"></script>
		<script src="../templates/mostudio/js/bootstrap.min.js"></script>
		<script src="../templates/mostudio/js/jquery.easing.1.3.js"></script>
		<script src="../templates/mostudio/js/jquery.waypoints.min.js"></script>
		<script src="../templates/mostudio/js/jquery.stellar.min.js"></script>
		<script src="../templates/mostudio/js/owl.carousel.min.js"></script>
		<script src="../templates/mostudio/js/jquery.magnific-popup.min.js"></script>
		<script src="../templates/mostudio/js/jquery.animateNumber.min.js"></script>
		<script src="../templates/mostudio/js/scrollax.min.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
		<script src="../templates/mostudio/js/google-map.js"></script>
		<script src="../templates/mostudio/js/main.js"></script>
		
	</body>
	</html>