<section class="page-section bg-primary text-white mb-0" id="login">
    <div class="container">
		<h1>Přihlášení do administrace</h1>
		<form method="post">
			Jméno<br />
			<input type="text" name="jmeno" /><br />
			Heslo<br />
			<input type="password" name="heslo" /><br />
			<input type="submit" value="Přihlásit" />
		</form>

		<p>Pokud ještě nemáte účet, <a href="registrace" style="background-color:powderblue">zaregistrujte se</a>.</p>
	</div>
</section>