        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="editorial">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white"><?= $titulek ?></h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                

                <!-- About Section Content-->
                <div class="row">
					<div class="col-lg-6 ms-auto"><p class="lead"><?= $_obsah ?>
					</div>
                    <div class="col-lg-6 me-auto">
                        <p class="lead">Přehled všech uložených templates.
                            Odkazem <a href="template/all#summary" style="background-color:powderblue">Přehled</a> lze otevřít náhled dostupných uložených nastavení. Nastavení je soupis všech parametrů, které je možné na výsledných webech měnit-upravovat.</p>
						<br /><br />
                            <div class="col">
                                <p>Formulář pro nový web!</p>
                                Pokud potřebuje vložit vlatní data-přizpůsobit obsah webu svojí představě založte si vlastní profil obsahují nastavení svých textů a údajů, ze kterých se bude web skládat.
                            </div>
                            <br />
                            <p class="lead">
                                <a href="templator#templator" style="background-color:powderblue">Vytvořit nový web-vyplň formulář</a>
                            </p>
                            <br />
                        <div>
                            Editovat poslední nastavený testovací profil...
                            <a href="templator/kluci#templator" style="background-color:powderblue">Editovat</a>
                        </div>
                    </div>
                </div>
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                </div>
            </div>
        </section>
